import "load-env";
import { pgDb as db } from "lib/db/pg/db.pg";
import { DepartmentSchema, CourseSchema } from "lib/db/pg/schema.pg";

console.log("🎓 Seeding MIVA University - 14 Majors with All Courses");

async function seedMajorsAndCourses() {
  try {
    // 14 Majors treated as departments
    const majors = [
      {
        code: "CS",
        name: "Computer Science",
        description: "Study of computation, algorithms, and software development",
      },
      {
        code: "CYB",
        name: "Cybersecurity",
        description: "Focus on information security and cyber defense",
      },
      {
        code: "DTS",
        name: "Data Science",
        description: "Big data analytics, machine learning, and data visualization",
      },
      {
        code: "SEN",
        name: "Software Engineering",
        description: "Software design, development, and project management",
      },
      {
        code: "ITE",
        name: "Information Technology",
        description: "IT systems, networks, and technology management",
      },
      {
        code: "BUA",
        name: "Business Management",
        description: "Business administration, operations, and strategy",
      },
      {
        code: "ECO",
        name: "Economics",
        description: "Economic theory, analysis, and policy",
      },
      {
        code: "ACC",
        name: "Accounting",
        description: "Financial accounting, auditing, and taxation",
      },
      {
        code: "PAD",
        name: "Public Policy and Administration",
        description: "Public administration, governance, and policy analysis",
      },
      {
        code: "CSS",
        name: "Criminology and Security Studies",
        description: "Criminal justice, law enforcement, and security",
      },
      {
        code: "MCM",
        name: "Mass Communication and Media Studies",
        description: "Journalism, broadcasting, advertising, and public relations",
      },
      {
        code: "NSC",
        name: "Nursing Science",
        description: "Nursing practice, healthcare, and patient care",
      },
      {
        code: "PHS",
        name: "Public Health",
        description: "Public health, epidemiology, and health systems",
      },
    ];

    // Step 1: Create departments (14 majors)
    console.log("📚 Creating 14 majors as departments...");
    const departments = await db
      .insert(DepartmentSchema)
      .values(majors)
      .returning();

    console.log(`✅ Created ${departments.length} majors`);

    // Create department map for courses
    const deptMap: Record<string, string> = {};
    for (const dept of departments) {
      deptMap[dept.code] = dept.id;
    }

    // Step 2: All courses with their major codes
    console.log("📖 Creating all courses...");
    const allCourses = [
      // Computer Science courses
      { courseCode: "GST111", title: "Communication in English I", level: "100L", semester: "fall", major: "CS" },
      { courseCode: "MTH101", title: "Elementary Mathematics I – Algebra and Trigonometry", level: "100L", semester: "fall", major: "CS" },
      { courseCode: "PHY101", title: "General Physics I – Mechanics", level: "100L", semester: "fall", major: "CS" },
      { courseCode: "PHY107", title: "General Practical Physics I", level: "100L", semester: "fall", major: "CS" },
      { courseCode: "GST121", title: "Use of Library, Study Skills and ICT", level: "100L", semester: "fall", major: "CS" },
      { courseCode: "STA111", title: "Descriptive Statistics", level: "100L", semester: "fall", major: "CS" },
      { courseCode: "COS101", title: "Introduction to Computing Sciences", level: "100L", semester: "fall", major: "CS" },
      { courseCode: "COS102", title: "Problem Solving", level: "100L", semester: "spring", major: "CS" },
      { courseCode: "GST112", title: "Nigerian People and Culture", level: "100L", semester: "spring", major: "CS" },
      { courseCode: "MTH102", title: "Elementary Mathematics II – Calculus", level: "100L", semester: "spring", major: "CS" },
      { courseCode: "PHY102", title: "General Physics II – Electricity & Magnetism", level: "100L", semester: "spring", major: "CS" },
      { courseCode: "PHY108", title: "General Practical Physics II", level: "100L", semester: "spring", major: "CS" },
      { courseCode: "CSC106", title: "Introduction to Web Technologies", level: "100L", semester: "spring", major: "CS" },
      { courseCode: "GST122", title: "Communication in English II", level: "100L", semester: "spring", major: "CS" },
      { courseCode: "ENT211", title: "Entrepreneurship and Innovation", level: "200L", semester: "fall", major: "CS" },
      { courseCode: "MTH201", title: "Mathematical Methods I", level: "200L", semester: "fall", major: "CS" },
      { courseCode: "COS201", title: "Computer Programming I", level: "200L", semester: "fall", major: "CS" },
      { courseCode: "COS203", title: "Discrete Structures", level: "200L", semester: "fall", major: "CS" },
      { courseCode: "IFT211", title: "Digital Logic Design", level: "200L", semester: "fall", major: "CS" },
      { courseCode: "SEN201", title: "Introduction to Software Engineering", level: "200L", semester: "fall", major: "CS" },
      { courseCode: "GST212", title: "Philosophy, Logic and Human Existence", level: "200L", semester: "spring", major: "CS" },
      { courseCode: "MTH202", title: "Elementary Differential Equations", level: "200L", semester: "spring", major: "CS" },
      { courseCode: "COS202", title: "Computer Programming II", level: "200L", semester: "spring", major: "CS" },
      { courseCode: "IFT212", title: "Computer Architecture and Organisation", level: "200L", semester: "spring", major: "CS" },
      { courseCode: "CSC204", title: "Statistical Computing Inference and Modelling", level: "200L", semester: "spring", major: "CS" },
      { courseCode: "MTH204", title: "Linear Algebra II", level: "200L", semester: "spring", major: "CS" },
      { courseCode: "PHY202", title: "Introduction to Electric Circuits and Electronics", level: "200L", semester: "spring", major: "CS" },
      { courseCode: "CSC301", title: "Data Structures", level: "300L", semester: "fall", major: "CS" },
      { courseCode: "CSC309", title: "Artificial Intelligence", level: "300L", semester: "fall", major: "CS" },
      { courseCode: "CYB201", title: "Introduction to Cyber Security and Strategy", level: "300L", semester: "fall", major: "CS" },
      { courseCode: "CSC303", title: "Introduction to Data Management", level: "300L", semester: "fall", major: "CS" },
      { courseCode: "ICT305", title: "Data Communication System and Network", level: "300L", semester: "fall", major: "CS" },
      { courseCode: "GST312", title: "Peace and Conflict Resolution", level: "300L", semester: "spring", major: "CS" },
      { courseCode: "ENT312", title: "Venture Creation", level: "300L", semester: "spring", major: "CS" },

      // Computer Science 400L courses
      { courseCode: "CSC401", title: "Research Methodology and Technical Report Writing", level: "400L", semester: "fall", major: "CS" },
      { courseCode: "CSC402", title: "Algorithms and Complexity Analysis", level: "400L", semester: "fall", major: "CS" },
      { courseCode: "CSC403", title: "Project Management", level: "400L", semester: "fall", major: "CS" },
      { courseCode: "CSC404", title: "Distributed Computing", level: "400L", semester: "fall", major: "CS" },
      { courseCode: "CSC405", title: "Organization of Programming Languages", level: "400L", semester: "fall", major: "CS" },
      { courseCode: "CSC406", title: "Final Year Project I", level: "400L", semester: "fall", major: "CS" },
      { courseCode: "CSC407", title: "Ethical and Legal Issues in Computer Science", level: "400L", semester: "spring", major: "CS" },
      { courseCode: "CSC408", title: "Machine Learning", level: "400L", semester: "spring", major: "CS" },
      { courseCode: "CSC409", title: "Human Computer Interaction", level: "400L", semester: "spring", major: "CS" },
      { courseCode: "CSC410", title: "Final Year Project II", level: "400L", semester: "spring", major: "CS" },
      { courseCode: "CSC411", title: "Compiler Construction", level: "400L", semester: "spring", major: "CS" },
      { courseCode: "CSC412", title: "Cloud Computing Security", level: "400L", semester: "spring", major: "CS" },

      // Cybersecurity courses
      { courseCode: "CYB203", title: "Cybercrime, Law and Countermeasures", level: "200L", semester: "fall", major: "CYB" },
      { courseCode: "CYB204", title: "Computer Networks", level: "200L", semester: "spring", major: "CYB" },
      { courseCode: "CYB301", title: "Cryptography Techniques, Algorithms and Applications", level: "300L", semester: "fall", major: "CYB" },
      { courseCode: "CYB303", title: "Cybersecurity Risks Analysis, Challenges and Mitigation", level: "300L", semester: "fall", major: "CYB" },
      { courseCode: "CYB305", title: "Digital Forensics and Investigation Methods", level: "300L", semester: "fall", major: "CYB" },
      { courseCode: "CYB307", title: "System and Network Administration", level: "300L", semester: "fall", major: "CYB" },
      { courseCode: "CYB309", title: "Cyber Security in Business and Industries", level: "300L", semester: "fall", major: "CYB" },

      // Data Science courses
      { courseCode: "DTS201", title: "Introduction to Data Science", level: "200L", semester: "fall", major: "DTS" },
      { courseCode: "DTS202", title: "Data Engineering", level: "200L", semester: "spring", major: "DTS" },
      { courseCode: "DTS204", title: "Statistical Computing Inference and Modelling", level: "200L", semester: "spring", major: "DTS" },
      { courseCode: "DTS206", title: "Linear Algebra for Data Science", level: "200L", semester: "spring", major: "DTS" },
      { courseCode: "DTS211", title: "Introduction to R Programming", level: "200L", semester: "fall", major: "DTS" },
      { courseCode: "MTH203", title: "Set, Logic, and Algebra", level: "200L", semester: "fall", major: "DTS" },
      { courseCode: "MTH209", title: "Introduction to Numerical Analysis", level: "200L", semester: "fall", major: "DTS" },
      { courseCode: "DTS301", title: "Data Structures", level: "300L", semester: "fall", major: "DTS" },
      { courseCode: "DTS305", title: "Data Quality and Data Wrangling", level: "300L", semester: "fall", major: "DTS" },
      { courseCode: "DTS317", title: "Introduction to Data Protection and IT Security", level: "300L", semester: "fall", major: "DTS" },
      { courseCode: "DTS319", title: "Internet of Things", level: "300L", semester: "fall", major: "DTS" },

      // Software Engineering courses
      { courseCode: "SEN203", title: "Software Requirements Engineering", level: "200L", semester: "fall", major: "SEN" },
      { courseCode: "SEN206", title: "Software Engineering Process", level: "200L", semester: "spring", major: "SEN" },
      { courseCode: "SEN212", title: "Sustainable Computing", level: "200L", semester: "spring", major: "SEN" },
      { courseCode: "SEN301", title: "Object-Oriented Analysis and Design", level: "300L", semester: "fall", major: "SEN" },
      { courseCode: "SEN305", title: "Software Defined Networking", level: "300L", semester: "fall", major: "SEN" },
      { courseCode: "SEN311", title: "Web Application Development", level: "300L", semester: "fall", major: "SEN" },

      // Information Technology courses
      { courseCode: "ITE101", title: "Introduction to Computing Sciences", level: "100L", semester: "fall", major: "ITE" },
      { courseCode: "ITE102", title: "Problem Solving", level: "100L", semester: "spring", major: "ITE" },
      { courseCode: "ITE112", title: "Principles of Hardware Systems Maintenance", level: "100L", semester: "spring", major: "ITE" },
      { courseCode: "ITE201", title: "Introduction to Web Technologies", level: "200L", semester: "fall", major: "ITE" },
      { courseCode: "ITE203", title: "Computer Programming I", level: "200L", semester: "fall", major: "ITE" },
      { courseCode: "ITE204", title: "Computer Programming II", level: "200L", semester: "spring", major: "ITE" },
      { courseCode: "ITE205", title: "Introduction to Information Technology", level: "200L", semester: "fall", major: "ITE" },
      { courseCode: "ITE206", title: "Human-Computer Interface", level: "200L", semester: "spring", major: "ITE" },
      { courseCode: "ITE212", title: "Introduction to Information Systems for Information Technology", level: "200L", semester: "fall", major: "ITE" },
      { courseCode: "ITE213", title: "Computer Architecture and Organisation", level: "200L", semester: "spring", major: "ITE" },
      { courseCode: "ITE214", title: "Systems Analysis and Design for Information Technology", level: "200L", semester: "spring", major: "ITE" },
      { courseCode: "ITE215", title: "Data Engineering", level: "200L", semester: "spring", major: "ITE" },
      { courseCode: "ITE301", title: "Computer Graphics and Animation", level: "300L", semester: "fall", major: "ITE" },
      { courseCode: "ITE302", title: "Web Application Development", level: "300L", semester: "spring", major: "ITE" },
      { courseCode: "ITE303", title: "Operating Systems", level: "300L", semester: "spring", major: "ITE" },
      { courseCode: "ITE304", title: "Web Development using Content Management Systems", level: "300L", semester: "spring", major: "ITE" },
      { courseCode: "ITE305", title: "Data Communications Systems and Network", level: "300L", semester: "fall", major: "ITE" },
      { courseCode: "ITE306", title: "Mobile Application Development", level: "300L", semester: "spring", major: "ITE" },
      { courseCode: "ITE307", title: "Edge Computing", level: "300L", semester: "fall", major: "ITE" },
      { courseCode: "ITE308", title: "IT Innovation and Entrepreneurship", level: "300L", semester: "spring", major: "ITE" },
      { courseCode: "ITE309", title: "Distributed Information Systems", level: "300L", semester: "fall", major: "ITE" },
      { courseCode: "ITE310", title: "Network Servers and Infrastructures", level: "300L", semester: "spring", major: "ITE" },
      { courseCode: "ITE311", title: "Ethics and Legal Issues in IT", level: "300L", semester: "spring", major: "ITE" },
      { courseCode: "ITE401", title: "Research Methodology and Technical Report Writing", level: "400L", semester: "fall", major: "ITE" },
      { courseCode: "ITE402", title: "System Integration and Architecture", level: "400L", semester: "spring", major: "ITE" },
      { courseCode: "ITE403", title: "Mobile and Pervasive Computing", level: "400L", semester: "fall", major: "ITE" },
      { courseCode: "ITE404", title: "Wireless Communications and Networking", level: "400L", semester: "spring", major: "ITE" },
      { courseCode: "ITE405", title: "Project Management", level: "400L", semester: "fall", major: "ITE" },
      { courseCode: "ITE406", title: "Introduction to Embedded Systems", level: "400L", semester: "spring", major: "ITE" },
      { courseCode: "ITE407", title: "Distributed Computing for Information Technology", level: "400L", semester: "fall", major: "ITE" },
      { courseCode: "ITE408", title: "Cloud Computing Security for Information Technology", level: "400L", semester: "spring", major: "ITE" },
      { courseCode: "ITE409", title: "Sustainable Computing", level: "400L", semester: "fall", major: "ITE" },
      { courseCode: "ITE410", title: "Internet of Things", level: "400L", semester: "spring", major: "ITE" },
      { courseCode: "ITE411", title: "Final Year Project I", level: "400L", semester: "fall", major: "ITE" },
      { courseCode: "ITE412", title: "Final Year Project II", level: "400L", semester: "spring", major: "ITE" },

      // Business Management courses
      { courseCode: "BUA101", title: "Principles of Management", level: "100L", semester: "fall", major: "BUA" },
      { courseCode: "BUA102", title: "Principles of Project Management", level: "100L", semester: "spring", major: "BUA" },
      { courseCode: "BUA103", title: "Introduction to Business I", level: "100L", semester: "fall", major: "BUA" },
      { courseCode: "BUA104", title: "Introduction to Business II", level: "100L", semester: "spring", major: "BUA" },
      { courseCode: "BUA105", title: "Introduction to Financial Accounting", level: "100L", semester: "fall", major: "BUA" },
      { courseCode: "BUA106", title: "Principles of Management II", level: "100L", semester: "spring", major: "BUA" },
      { courseCode: "BUA107", title: "Introduction to Computing", level: "100L", semester: "fall", major: "BUA" },
      { courseCode: "BUA201", title: "Business Statistics", level: "200L", semester: "fall", major: "BUA" },
      { courseCode: "BUA202", title: "Principles of Business Administration II", level: "200L", semester: "spring", major: "BUA" },
      { courseCode: "BUA203", title: "Principles of Business Administration I", level: "200L", semester: "fall", major: "BUA" },
      { courseCode: "BUA204", title: "Green Management", level: "200L", semester: "spring", major: "BUA" },
      { courseCode: "BUA205", title: "Current Issues in Global Business", level: "200L", semester: "fall", major: "BUA" },
      { courseCode: "BUA206", title: "Introduction to Financial Management", level: "200L", semester: "spring", major: "BUA" },
      { courseCode: "BUA207", title: "Leadership and Governance", level: "200L", semester: "fall", major: "BUA" },
      { courseCode: "BUA208", title: "Quantitative Analysis in Management", level: "200L", semester: "spring", major: "BUA" },
      { courseCode: "BUA209", title: "Elements of marketing", level: "200L", semester: "fall", major: "BUA" },
      { courseCode: "BUA210", title: "Business Environment", level: "200L", semester: "spring", major: "BUA" },
      { courseCode: "BUA301", title: "Management Theory", level: "300L", semester: "fall", major: "BUA" },
      { courseCode: "BUA302", title: "Human Behaviour in Organisations", level: "300L", semester: "spring", major: "BUA" },
      { courseCode: "BUA303", title: "Financial Management", level: "300L", semester: "fall", major: "BUA" },
      { courseCode: "BUA304", title: "Human Resources Management", level: "300L", semester: "spring", major: "BUA" },
      { courseCode: "BUA305", title: "Innovation Management", level: "300L", semester: "fall", major: "BUA" },
      { courseCode: "BUA306", title: "Production and Operations Management", level: "300L", semester: "spring", major: "BUA" },
      { courseCode: "BUA307", title: "E-Commerce", level: "300L", semester: "fall", major: "BUA" },
      { courseCode: "BUA308", title: "Small Business Management", level: "300L", semester: "spring", major: "BUA" },
      { courseCode: "BUA309", title: "Business Start-up", level: "300L", semester: "fall", major: "BUA" },
      { courseCode: "BUA310", title: "Research Methods in Business", level: "300L", semester: "spring", major: "BUA" },
      { courseCode: "BUA311", title: "Supply Chain Management", level: "300L", semester: "fall", major: "BUA" },
      { courseCode: "BUA313", title: "Business Law", level: "300L", semester: "fall", major: "BUA" },
      { courseCode: "BUA401", title: "Business Policy and Strategic Management", level: "400L", semester: "fall", major: "BUA" },
      { courseCode: "BUA402", title: "Strategic Thinking and Problem Solving", level: "400L", semester: "spring", major: "BUA" },
      { courseCode: "BUA403", title: "Management Information System", level: "400L", semester: "fall", major: "BUA" },
      { courseCode: "BUA404", title: "Research project in Business Management", level: "400L", semester: "spring", major: "BUA" },
      { courseCode: "BUA405", title: "Analysis for Business Decision", level: "400L", semester: "fall", major: "BUA" },
      { courseCode: "BUA406", title: "International Business", level: "400L", semester: "spring", major: "BUA" },
      { courseCode: "BUA407", title: "Feasibility Report and Business Plan Analysis", level: "400L", semester: "fall", major: "BUA" },
      { courseCode: "BUA408", title: "Internship", level: "400L", semester: "spring", major: "BUA" },
      { courseCode: "BUA409", title: "Case Studies and Contemporary issues in Business", level: "400L", semester: "fall", major: "BUA" },
      { courseCode: "BUA410", title: "International Management", level: "400L", semester: "spring", major: "BUA" },
      { courseCode: "BUA411", title: "Business Entrepreneurship", level: "400L", semester: "fall", major: "BUA" },
      { courseCode: "BUA412", title: "Current Issues in Digital Economy and Business", level: "400L", semester: "spring", major: "BUA" },

      // Economics courses
      { courseCode: "ECO101", title: "Principles of Economics I", level: "100L", semester: "fall", major: "ECO" },
      { courseCode: "ECO102", title: "Principles of Economics II", level: "100L", semester: "spring", major: "ECO" },
      { courseCode: "ACC101", title: "Introduction to Financial Accounting I", level: "100L", semester: "fall", major: "ECO" },
      { courseCode: "ACC102", title: "Introduction to Financial Accounting II", level: "100L", semester: "spring", major: "ECO" },
      { courseCode: "STA112", title: "Introduction to Statistics II", level: "100L", semester: "spring", major: "ECO" },
      { courseCode: "ECO201", title: "Introduction to Microeconomics I", level: "200L", semester: "fall", major: "ECO" },
      { courseCode: "ECO202", title: "Introduction to Computer and its Application", level: "200L", semester: "spring", major: "ECO" },
      { courseCode: "ECO203", title: "Introduction to Macroeconomics I", level: "200L", semester: "fall", major: "ECO" },
      { courseCode: "ECO204", title: "Introduction to Microeconomics II", level: "200L", semester: "spring", major: "ECO" },
      { courseCode: "ECO205", title: "Structure of the Nigerian Economy", level: "200L", semester: "fall", major: "ECO" },
      { courseCode: "ECO206", title: "Introduction to Macroeconomics II", level: "200L", semester: "spring", major: "ECO" },
      { courseCode: "ECO207", title: "Mathematics for Economists", level: "200L", semester: "fall", major: "ECO" },
      { courseCode: "ECO208", title: "Statistics for Economist", level: "200L", semester: "spring", major: "ECO" },
      { courseCode: "ECO209", title: "Financial Markets and Monetary Economics", level: "200L", semester: "fall", major: "ECO" },
      { courseCode: "ECO210", title: "Behavioural Economics", level: "200L", semester: "spring", major: "ECO" },
      { courseCode: "ECO212", title: "Introduction to Decision Science", level: "200L", semester: "spring", major: "ECO" },
      { courseCode: "ECO214", title: "Introduction to Health Economics", level: "200L", semester: "spring", major: "ECO" },
      { courseCode: "ECO216", title: "Labour Economics", level: "200L", semester: "spring", major: "ECO" },
      { courseCode: "ECO301", title: "Intermediate Microeconomic Theory I", level: "300L", semester: "fall", major: "ECO" },
      { courseCode: "ECO302", title: "Intermediate Microeconomics II", level: "300L", semester: "spring", major: "ECO" },
      { courseCode: "ECO303", title: "Intermediate Macroeconomic Theory I", level: "300L", semester: "fall", major: "ECO" },
      { courseCode: "ECO304", title: "Intermediate Macroeconomics II", level: "300L", semester: "spring", major: "ECO" },
      { courseCode: "ECO305", title: "History of Economic Thought", level: "300L", semester: "fall", major: "ECO" },
      { courseCode: "ECO306", title: "Introductory Econometrics", level: "300L", semester: "spring", major: "ECO" },
      { courseCode: "ECO307", title: "Project Evaluation", level: "300L", semester: "fall", major: "ECO" },
      { courseCode: "ECO308", title: "Public Sector Economics", level: "300L", semester: "spring", major: "ECO" },
      { courseCode: "ECO309", title: "Innovation in the Social Sciences", level: "300L", semester: "fall", major: "ECO" },
      { courseCode: "ECO310", title: "International Economics", level: "300L", semester: "spring", major: "ECO" },
      { courseCode: "ECO311", title: "Data Analytics and Visualization", level: "300L", semester: "fall", major: "ECO" },
      { courseCode: "ECO312", title: "Research Methods I", level: "300L", semester: "spring", major: "ECO" },
      { courseCode: "ECO313", title: "Development Economics", level: "300L", semester: "fall", major: "ECO" },
      { courseCode: "ECO401", title: "Advanced Microeconomics I", level: "400L", semester: "fall", major: "ECO" },
      { courseCode: "ECO402", title: "Advanced Microeconomics II", level: "400L", semester: "spring", major: "ECO" },
      { courseCode: "ECO403", title: "Advanced Macroeconomics I", level: "400L", semester: "fall", major: "ECO" },
      { courseCode: "ECO404", title: "Advanced Macroeconomics II", level: "400L", semester: "spring", major: "ECO" },
      { courseCode: "ECO405", title: "Economic Planning", level: "400L", semester: "fall", major: "ECO" },
      { courseCode: "ECO406", title: "Monetary Theory and Policy", level: "400L", semester: "spring", major: "ECO" },
      { courseCode: "ECO407", title: "Fiscal Policy and Analysis", level: "400L", semester: "fall", major: "ECO" },
      { courseCode: "ECO408", title: "Research Project/Original Essay", level: "400L", semester: "spring", major: "ECO" },
      { courseCode: "ECO409", title: "Research Method II", level: "400L", semester: "fall", major: "ECO" },
      { courseCode: "ECO410", title: "Economics and Decision Sciences", level: "400L", semester: "spring", major: "ECO" },
      { courseCode: "ECO411", title: "Advanced Econometrics", level: "400L", semester: "fall", major: "ECO" },
      { courseCode: "ECO413", title: "Environmental Economics", level: "400L", semester: "fall", major: "ECO" },

      // Accounting courses
      { courseCode: "ACC105", title: "Introduction to Finance", level: "100L", semester: "fall", major: "ACC" },
      { courseCode: "ACC107", title: "Introduction to Computing", level: "100L", semester: "fall", major: "ACC" },
      { courseCode: "ACC201", title: "Financial Accounting I", level: "200L", semester: "fall", major: "ACC" },
      { courseCode: "ACC202", title: "Financial Accounting II", level: "200L", semester: "spring", major: "ACC" },
      { courseCode: "ACC203", title: "Corporate Governance and Accounting Ethics", level: "200L", semester: "fall", major: "ACC" },
      { courseCode: "ACC204", title: "Commercial Law for Accountants II", level: "200L", semester: "spring", major: "ACC" },
      { courseCode: "ACC205", title: "Data Analytics in Accounting I", level: "200L", semester: "fall", major: "ACC" },
      { courseCode: "ACC206", title: "Accounting Laboratory/Technology", level: "200L", semester: "spring", major: "ACC" },
      { courseCode: "ACC207", title: "Commercial Law for Accountants", level: "200L", semester: "fall", major: "ACC" },
      { courseCode: "ACC208", title: "Capital Markets and Portfolio Theory", level: "200L", semester: "spring", major: "ACC" },
      { courseCode: "ACC209", title: "Petroleum Accounting", level: "200L", semester: "fall", major: "ACC" },
      { courseCode: "ACC210", title: "Cost Accounting", level: "200L", semester: "spring", major: "ACC" },
      { courseCode: "ACC212", title: "Leadership Skills", level: "200L", semester: "spring", major: "ACC" },
      { courseCode: "ACC301", title: "Financial Reporting I", level: "300L", semester: "fall", major: "ACC" },
      { courseCode: "ACC302", title: "Financial Reporting II", level: "300L", semester: "spring", major: "ACC" },
      { courseCode: "ACC303", title: "Management Accounting", level: "300L", semester: "fall", major: "ACC" },
      { courseCode: "ACC304", title: "Taxation II", level: "300L", semester: "spring", major: "ACC" },
      { courseCode: "ACC305", title: "Taxation I", level: "300L", semester: "fall", major: "ACC" },
      { courseCode: "ACC306", title: "Public Sector Accounting & Reporting", level: "300L", semester: "spring", major: "ACC" },
      { courseCode: "ACC307", title: "Auditing and Assurance I", level: "300L", semester: "fall", major: "ACC" },
      { courseCode: "ACC308", title: "Research Methods in Accounting", level: "300L", semester: "spring", major: "ACC" },
      { courseCode: "ACC309", title: "Entrepreneurship in Accounting Education", level: "300L", semester: "fall", major: "ACC" },
      { courseCode: "ACC310", title: "Intermediate Accounting II", level: "300L", semester: "spring", major: "ACC" },
      { courseCode: "ACC311", title: "Company Law I", level: "300L", semester: "fall", major: "ACC" },
      { courseCode: "ACC312", title: "Company Law II", level: "300L", semester: "spring", major: "ACC" },
      { courseCode: "ACC313", title: "Intermediate Accounting I", level: "300L", semester: "fall", major: "ACC" },
      { courseCode: "ACC401", title: "Advanced Financial Reporting", level: "400L", semester: "fall", major: "ACC" },
      { courseCode: "ACC402", title: "Financial Management", level: "400L", semester: "spring", major: "ACC" },
      { courseCode: "ACC403", title: "Auditing and Assurance II", level: "400L", semester: "fall", major: "ACC" },
      { courseCode: "ACC404", title: "Corporate Reporting", level: "400L", semester: "spring", major: "ACC" },
      { courseCode: "ACC405", title: "Taxation and Tax Management I", level: "400L", semester: "fall", major: "ACC" },
      { courseCode: "ACC406", title: "Advanced Financial Accounting", level: "400L", semester: "spring", major: "ACC" },
      { courseCode: "ACC407", title: "Advanced Management Accounting I", level: "400L", semester: "fall", major: "ACC" },
      { courseCode: "ACC408", title: "Research Project", level: "400L", semester: "spring", major: "ACC" },
      { courseCode: "ACC409", title: "Bankruptcy and Liquidation", level: "400L", semester: "fall", major: "ACC" },
      { courseCode: "ACC410", title: "Taxation and Tax Management II", level: "400L", semester: "spring", major: "ACC" },
      { courseCode: "ACC411", title: "International Accounting", level: "400L", semester: "fall", major: "ACC" },
      { courseCode: "ACC412", title: "Advanced Management Accounting II", level: "400L", semester: "spring", major: "ACC" },

      // Public Policy and Administration courses
      { courseCode: "PAD101", title: "Elements of Public Administration", level: "100L", semester: "fall", major: "PAD" },
      { courseCode: "PAD102", title: "Organisation of Government", level: "100L", semester: "spring", major: "PAD" },
      { courseCode: "PAD103", title: "Introduction to Political Science I", level: "100L", semester: "fall", major: "PAD" },
      { courseCode: "PAD105", title: "Introduction to Computing", level: "100L", semester: "fall", major: "PAD" },
      { courseCode: "PAD201", title: "Introduction to Public Administration", level: "200L", semester: "fall", major: "PAD" },
      { courseCode: "PAD202", title: "Nigeria Government and Administration", level: "200L", semester: "spring", major: "PAD" },
      { courseCode: "PAD203", title: "Office Administration", level: "200L", semester: "fall", major: "PAD" },
      { courseCode: "PAD204", title: "Rural and Community Development", level: "200L", semester: "spring", major: "PAD" },
      { courseCode: "PAD205", title: "Nigerian Legal System", level: "200L", semester: "fall", major: "PAD" },
      { courseCode: "PAD206", title: "Policy Process", level: "200L", semester: "spring", major: "PAD" },
      { courseCode: "PAD207", title: "Introduction to Public Policy Analysis and Decision Making", level: "200L", semester: "fall", major: "PAD" },
      { courseCode: "PAD208", title: "Contemporary Strategic Studies", level: "200L", semester: "spring", major: "PAD" },
      { courseCode: "PAD209", title: "Foreign Policy Making and Analysis", level: "200L", semester: "fall", major: "PAD" },
      { courseCode: "PAD210", title: "Quantitative Methods in Decision Making", level: "200L", semester: "spring", major: "PAD" },
      { courseCode: "PAD212", title: "Strategic Leadership", level: "200L", semester: "spring", major: "PAD" },
      { courseCode: "PAD301", title: "Administrative Theory", level: "300L", semester: "fall", major: "PAD" },
      { courseCode: "PAD302", title: "Administrative Behaviour", level: "300L", semester: "spring", major: "PAD" },
      { courseCode: "PAD303", title: "International Administration", level: "300L", semester: "fall", major: "PAD" },
      { courseCode: "PAD304", title: "Development Administration", level: "300L", semester: "spring", major: "PAD" },
      { courseCode: "PAD305", title: "Public Personnel Administration", level: "300L", semester: "fall", major: "PAD" },
      { courseCode: "PAD306", title: "E-Governance", level: "300L", semester: "spring", major: "PAD" },
      { courseCode: "PAD307", title: "Research Methods", level: "300L", semester: "fall", major: "PAD" },
      { courseCode: "PAD308", title: "Intergovernmental relations", level: "300L", semester: "spring", major: "PAD" },
      { courseCode: "PAD309", title: "Public Finance", level: "300L", semester: "fall", major: "PAD" },
      { courseCode: "PAD310", title: "Traditional Administrative System in Nigeria", level: "300L", semester: "spring", major: "PAD" },
      { courseCode: "PAD311", title: "Administrative Law", level: "300L", semester: "fall", major: "PAD" },
      { courseCode: "PAD312", title: "Policy Evaluation", level: "300L", semester: "spring", major: "PAD" },
      { courseCode: "PAD313", title: "Comparative Local Government", level: "300L", semester: "fall", major: "PAD" },
      { courseCode: "PAD401", title: "Theory and Practice of Planning", level: "400L", semester: "fall", major: "PAD" },
      { courseCode: "PAD402", title: "Public Project Analysis and Management", level: "400L", semester: "spring", major: "PAD" },
      { courseCode: "PAD403", title: "Public Policy Analysis", level: "400L", semester: "fall", major: "PAD" },
      { courseCode: "PAD404", title: "Public Enterprises Management", level: "400L", semester: "spring", major: "PAD" },
      { courseCode: "PAD405", title: "Workshop in Public Administration", level: "400L", semester: "fall", major: "PAD" },
      { courseCode: "PAD406", title: "Research Project", level: "400L", semester: "spring", major: "PAD" },
      { courseCode: "PAD407", title: "Public Finance Administration", level: "400L", semester: "fall", major: "PAD" },
      { courseCode: "PAD408", title: "Comparative Public Administration", level: "400L", semester: "spring", major: "PAD" },
      { courseCode: "PAD409", title: "Public Service Ethics and Accountability", level: "400L", semester: "fall", major: "PAD" },
      { courseCode: "PAD410", title: "Legislative Process", level: "400L", semester: "spring", major: "PAD" },
      { courseCode: "PAD411", title: "Social and Welfare Administration in Nigeria", level: "400L", semester: "fall", major: "PAD" },
      { courseCode: "PAD413", title: "Theory and Practice of Industrial Relations", level: "400L", semester: "fall", major: "PAD" },

      // Criminology and Security Studies courses
      { courseCode: "CSS101", title: "Introduction to Criminology and Security Studies", level: "100L", semester: "fall", major: "CSS" },
      { courseCode: "CSS102", title: "Introduction to Criminal Justice System", level: "100L", semester: "spring", major: "CSS" },
      { courseCode: "CSS103", title: "Deviant Behaviours and Social Control", level: "100L", semester: "fall", major: "CSS" },
      { courseCode: "CSS104", title: "Social Sciences and Human Behaviours", level: "100L", semester: "spring", major: "CSS" },
      { courseCode: "CSS105", title: "Introduction to Sociology I", level: "100L", semester: "fall", major: "CSS" },
      { courseCode: "CSS106", title: "Introduction to Sociology II", level: "100L", semester: "spring", major: "CSS" },
      { courseCode: "CSS107", title: "Introduction to Nigerian Criminal Law", level: "100L", semester: "fall", major: "CSS" },
      { courseCode: "CSS108", title: "Introduction to Law Enforcement", level: "100L", semester: "spring", major: "CSS" },
      { courseCode: "CSS109", title: "Sociology of Law", level: "100L", semester: "fall", major: "CSS" },
      { courseCode: "CSS110", title: "Theories of Crime", level: "100L", semester: "spring", major: "CSS" },
      { courseCode: "CSS111", title: "Introduction to Political Science", level: "100L", semester: "fall", major: "CSS" },
      { courseCode: "CSS112", title: "Nigerian Legal System", level: "100L", semester: "spring", major: "CSS" },
      { courseCode: "CSS113", title: "Introduction to Psychology", level: "100L", semester: "fall", major: "CSS" },
      { courseCode: "CSS114", title: "Determinants of Behaviour", level: "100L", semester: "spring", major: "CSS" },
      { courseCode: "CSS201", title: "Nigerian Law Enforcement and Security System", level: "200L", semester: "fall", major: "CSS" },
      { courseCode: "CSS202", title: "Introduction to Computer and its Application", level: "200L", semester: "spring", major: "CSS" },
      { courseCode: "CSS203", title: "Comparative Police and Policing Systems", level: "200L", semester: "fall", major: "CSS" },
      { courseCode: "CSS204", title: "Nigerian Criminal Procedure and Evidence", level: "200L", semester: "spring", major: "CSS" },
      { courseCode: "CSS205", title: "Human Rights and Criminal Justice System", level: "200L", semester: "fall", major: "CSS" },
      { courseCode: "CSS206", title: "Applied Statistical Methods in Criminology and Security Studies", level: "200L", semester: "spring", major: "CSS" },
      { courseCode: "CSS207", title: "Prisons and Correctional Services", level: "200L", semester: "fall", major: "CSS" },
      { courseCode: "CSS208", title: "Conflict Resolution and Peace Building", level: "200L", semester: "spring", major: "CSS" },
      { courseCode: "CSS209", title: "Sociology of Crime and Juvenile Delinquency", level: "200L", semester: "fall", major: "CSS" },
      { courseCode: "CSS210", title: "Crime, Harm and the State", level: "200L", semester: "spring", major: "CSS" },
      { courseCode: "CSS211", title: "Cybercrime, Law, and Countermeasures for Criminology", level: "200L", semester: "fall", major: "CSS" },
      { courseCode: "CSS301", title: "Innovation in the Social Sciences", level: "300L", semester: "fall", major: "CSS" },
      { courseCode: "CSS302", title: "Research Methods I", level: "300L", semester: "spring", major: "CSS" },
      { courseCode: "CSS303", title: "Theories of Crime, Criminal Behaviour and Punishment", level: "300L", semester: "fall", major: "CSS" },
      { courseCode: "CSS304", title: "Theoretical Perspectives on Security", level: "300L", semester: "spring", major: "CSS" },
      { courseCode: "CSS305", title: "Research Methods in Criminology and Security Studies", level: "300L", semester: "fall", major: "CSS" },
      { courseCode: "CSS306", title: "Intelligence & Investigation Management", level: "300L", semester: "spring", major: "CSS" },
      { courseCode: "CSS307", title: "Forensic Science", level: "300L", semester: "fall", major: "CSS" },
      { courseCode: "CSS308", title: "Internship/Organizational visits", level: "300L", semester: "spring", major: "CSS" },
      { courseCode: "CSS309", title: "Victimology", level: "300L", semester: "fall", major: "CSS" },
      { courseCode: "CSS310", title: "Contemporary Theories in Criminology and Security Studies", level: "300L", semester: "spring", major: "CSS" },
      { courseCode: "CSS311", title: "Corrupt Practices, Economic and Financial Crimes", level: "300L", semester: "fall", major: "CSS" },
      { courseCode: "CSS312", title: "Border Security and International Migration", level: "300L", semester: "spring", major: "CSS" },
      { courseCode: "CSS313", title: "Security, Road Safety and Traffic Control", level: "300L", semester: "fall", major: "CSS" },
      { courseCode: "CSS314", title: "Corporate and White-Collar Crimes", level: "300L", semester: "spring", major: "CSS" },
      { courseCode: "CSS315", title: "Security and Civil Defence Procedure", level: "300L", semester: "fall", major: "CSS" },
      { courseCode: "CSS401", title: "Research Methods II", level: "400L", semester: "fall", major: "CSS" },
      { courseCode: "CSS402", title: "Democracy and Governance of Security Sector", level: "400L", semester: "spring", major: "CSS" },
      { courseCode: "CSS403", title: "Research Project", level: "400L", semester: "fall", major: "CSS" },
      { courseCode: "CSS404", title: "Humanitarian Emergency and Disaster Management", level: "400L", semester: "spring", major: "CSS" },
      { courseCode: "CSS405", title: "Contemporary Development in Criminology and Security Studies", level: "400L", semester: "fall", major: "CSS" },
      { courseCode: "CSS406", title: "Comparative National Security Policy and Strategy", level: "400L", semester: "spring", major: "CSS" },
      { courseCode: "CSS407", title: "National and Transnational Organised Crimes", level: "400L", semester: "fall", major: "CSS" },
      { courseCode: "CSS408", title: "Criminological Theory and Social Policy", level: "400L", semester: "spring", major: "CSS" },
      { courseCode: "CSS409", title: "Terrorism, Counter-Terrorism and Insurgency", level: "400L", semester: "fall", major: "CSS" },
      { courseCode: "CSS410", title: "Digital Forensics, Investigation and Criminal Intelligence", level: "400L", semester: "spring", major: "CSS" },
      { courseCode: "CSS411", title: "Globalisation, Crime and Justice", level: "400L", semester: "fall", major: "CSS" },
      { courseCode: "CSS412", title: "Political Crime and Treasury Looting", level: "400L", semester: "spring", major: "CSS" },
      { courseCode: "CSS413", title: "Women, Gendered Confinement and Criminalisation", level: "400L", semester: "fall", major: "CSS" },
      { courseCode: "CSS414", title: "Racialization, Criminalization and Criminal Justice System", level: "400L", semester: "spring", major: "CSS" },
      { courseCode: "CSS416", title: "Crime Victims and Human Rights Violation", level: "400L", semester: "spring", major: "CSS" },
      { courseCode: "CSS418", title: "Crime and the Media", level: "400L", semester: "spring", major: "CSS" },

      // Mass Communication and Media Studies courses
      { courseCode: "MCM101", title: "Introduction to Human Communication", level: "100L", semester: "fall", major: "MCM" },
      { courseCode: "MCM102", title: "Writing for the Media", level: "100L", semester: "spring", major: "MCM" },
      { courseCode: "MCM103", title: "Foundations of Broadcasting and Film", level: "100L", semester: "fall", major: "MCM" },
      { courseCode: "MCM104", title: "Principles of Public Relations", level: "100L", semester: "spring", major: "MCM" },
      { courseCode: "MCM105", title: "Introduction to Advertising", level: "100L", semester: "fall", major: "MCM" },
      { courseCode: "MCM106", title: "Introduction to New Writing", level: "100L", semester: "spring", major: "MCM" },
      { courseCode: "MCM107", title: "Introduction to Book Publishing", level: "100L", semester: "fall", major: "MCM" },
      { courseCode: "MCM108", title: "African Communication Systems", level: "100L", semester: "spring", major: "MCM" },
      { courseCode: "MCM109", title: "Introduction to Photojournalism", level: "100L", semester: "fall", major: "MCM" },
      { courseCode: "MCM110", title: "Introduction to Electronic Media", level: "100L", semester: "spring", major: "MCM" },
      { courseCode: "MCM111", title: "History and Development of Mass Communication", level: "100L", semester: "fall", major: "MCM" },
      { courseCode: "MCM201", title: "History of Nigerian Media", level: "200L", semester: "fall", major: "MCM" },
      { courseCode: "MCM202", title: "Editing and Graphics of Communication", level: "200L", semester: "spring", major: "MCM" },
      { courseCode: "MCM203", title: "Critical and Reviewing Writing", level: "200L", semester: "fall", major: "MCM" },
      { courseCode: "MCM204", title: "Advanced and Specialised Reporting", level: "200L", semester: "spring", major: "MCM" },
      { courseCode: "MCM205", title: "Feature Writing", level: "200L", semester: "fall", major: "MCM" },
      { courseCode: "MCM206", title: "Manuscript Editing, Layout and Design in Book Publishing", level: "200L", semester: "spring", major: "MCM" },
      { courseCode: "MCM207", title: "Techniques in Book Publishing", level: "200L", semester: "fall", major: "MCM" },
      { courseCode: "MCM208", title: "Radio/Television Programme Writing", level: "200L", semester: "spring", major: "MCM" },
      { courseCode: "MCM209", title: "Radio/TV News Reporting and Production", level: "200L", semester: "fall", major: "MCM" },
      { courseCode: "MCM210", title: "Presentation and Performance", level: "200L", semester: "spring", major: "MCM" },
      { courseCode: "MCM211", title: "Drama, Film, and Documentary Production", level: "200L", semester: "fall", major: "MCM" },
      { courseCode: "MCM212", title: "Marketing Foundations for Public Relations and Advertising", level: "200L", semester: "spring", major: "MCM" },
      { courseCode: "MCM213", title: "Basics of Screenwriting and Film Animation", level: "200L", semester: "fall", major: "MCM" },
      { courseCode: "MCM214", title: "Advert Copywriting", level: "200L", semester: "spring", major: "MCM" },
      { courseCode: "MCM215", title: "Writing for Public Relations", level: "200L", semester: "fall", major: "MCM" },
      { courseCode: "MCM216", title: "Fundamentals of Media Relations", level: "200L", semester: "spring", major: "MCM" },
      { courseCode: "MCM217", title: "Advertising Media Planning", level: "200L", semester: "fall", major: "MCM" },
      { courseCode: "MCM301", title: "Theories of Communication", level: "300L", semester: "fall", major: "MCM" },
      { courseCode: "MCM302", title: "Foundations of Communication Research", level: "300L", semester: "spring", major: "MCM" },
      { courseCode: "MCM303", title: "Data Analysis in Communication Research", level: "300L", semester: "fall", major: "MCM" },
      { courseCode: "MCM304", title: "Online Journalism", level: "300L", semester: "spring", major: "MCM" },
      { courseCode: "MCM305", title: "Mass Communication and Politics", level: "300L", semester: "fall", major: "MCM" },
      { courseCode: "MCM306", title: "Foreign Correspondence", level: "300L", semester: "spring", major: "MCM" },
      { courseCode: "MCM307", title: "Gender and Communication", level: "300L", semester: "fall", major: "MCM" },
      { courseCode: "MCM308", title: "Investigative Journalism", level: "300L", semester: "spring", major: "MCM" },
      { courseCode: "MCM309", title: "Newspaper Management and Production", level: "300L", semester: "fall", major: "MCM" },
      { courseCode: "MCM310", title: "Broadcast Programming, Management and Operations", level: "300L", semester: "spring", major: "MCM" },
      { courseCode: "MCM311", title: "Photojournalism Research and Management", level: "300L", semester: "fall", major: "MCM" },
      { courseCode: "MCM312", title: "International and Foreign Broadcasting", level: "300L", semester: "spring", major: "MCM" },
      { courseCode: "MCM313", title: "Commentary, Critical Writing and Public Affairs Broadcasting", level: "300L", semester: "fall", major: "MCM" },
      { courseCode: "MCM314", title: "Organisation and Management of Advertising and Public Relations Agencies", level: "300L", semester: "spring", major: "MCM" },
      { courseCode: "MCM315", title: "Film Production and Screen Directing", level: "300L", semester: "fall", major: "MCM" },
      { courseCode: "MCM316", title: "International Public Relations and Advertising", level: "300L", semester: "spring", major: "MCM" },
      { courseCode: "MCM317", title: "Advertising and Public Relations Research", level: "300L", semester: "fall", major: "MCM" },
      { courseCode: "MCM319", title: "Consumer Affairs", level: "300L", semester: "fall", major: "MCM" },
      { courseCode: "MCM401", title: "International Communication", level: "400L", semester: "fall", major: "MCM" },
      { courseCode: "MCM402", title: "Communication and Society", level: "400L", semester: "spring", major: "MCM" },
      { courseCode: "MCM403", title: "Media Attachment/Internship", level: "400L", semester: "fall", major: "MCM" },
      { courseCode: "MCM404", title: "Original Research Project", level: "400L", semester: "spring", major: "MCM" },
      { courseCode: "MCM405", title: "Mass Media Law", level: "400L", semester: "fall", major: "MCM" },
      { courseCode: "MCM406", title: "Mass Media Ethics", level: "400L", semester: "spring", major: "MCM" },
      { courseCode: "MCM407", title: "Message Design for Development", level: "400L", semester: "fall", major: "MCM" },
      { courseCode: "MCM408", title: "Communication for Development", level: "400L", semester: "spring", major: "MCM" },
      { courseCode: "MCM409", title: "Media Management and Administration", level: "400L", semester: "fall", major: "MCM" },
      { courseCode: "MCM410", title: "Community Media and Relations", level: "400L", semester: "spring", major: "MCM" },
      { courseCode: "MCM411", title: "Immersive Communication", level: "400L", semester: "fall", major: "MCM" },
      { courseCode: "MCM412", title: "Social Media Management", level: "400L", semester: "spring", major: "MCM" },
      { courseCode: "MCM413", title: "Information Security and Digital Media", level: "400L", semester: "fall", major: "MCM" },

      // Nursing Science courses
      { courseCode: "NSC101", title: "Anatomy of Upper and Lower Limb", level: "100L", semester: "fall", major: "NSC" },
      { courseCode: "NSC102", title: "Renal and Body Fluids Physiology", level: "100L", semester: "spring", major: "NSC" },
      { courseCode: "NSC103", title: "General and Systemic Embryology", level: "100L", semester: "fall", major: "NSC" },
      { courseCode: "NSC104", title: "Anatomy of Thorax, Abdomen, Pelvis and Perineum", level: "100L", semester: "spring", major: "NSC" },
      { courseCode: "NSC105", title: "Introductory to Physiology and Blood", level: "100L", semester: "fall", major: "NSC" },
      { courseCode: "NSC106", title: "Biochemistry – General and Medical II", level: "100L", semester: "spring", major: "NSC" },
      { courseCode: "NSC107", title: "Biochemistry – General and Medical I", level: "100L", semester: "fall", major: "NSC" },
      { courseCode: "NSC108", title: "Foundations of Professional Nursing Practice II", level: "100L", semester: "spring", major: "NSC" },
      { courseCode: "NSC109", title: "Foundations of Professional Nursing Practice I", level: "100L", semester: "fall", major: "NSC" },
      { courseCode: "NSC110", title: "General and Cellular Pathology", level: "100L", semester: "spring", major: "NSC" },
      { courseCode: "NSC111", title: "Developmental Psychology", level: "100L", semester: "fall", major: "NSC" },
      { courseCode: "NSC113", title: "General Biochemistry Practical", level: "100L", semester: "fall", major: "NSC" },
      { courseCode: "NSC115", title: "Introduction to Computer Science I", level: "100L", semester: "fall", major: "NSC" },
      { courseCode: "NSC201", title: "Pharmacodynamics and Chemotherapy I", level: "200L", semester: "fall", major: "NSC" },
      { courseCode: "NSC202", title: "Community/Public Health Nursing II", level: "200L", semester: "spring", major: "NSC" },
      { courseCode: "NSC203", title: "Epidemiology", level: "200L", semester: "fall", major: "NSC" },
      { courseCode: "NSC204", title: "Medical and Surgical Nursing II", level: "200L", semester: "spring", major: "NSC" },
      { courseCode: "NSC205", title: "Community/Public Health Nursing I", level: "200L", semester: "fall", major: "NSC" },
      { courseCode: "NSC206", title: "Medical Surgical Nursing III", level: "200L", semester: "spring", major: "NSC" },
      { courseCode: "NSC207", title: "Human Nutrition", level: "200L", semester: "fall", major: "NSC" },
      { courseCode: "NSC208", title: "Medical Surgical Nursing Practicum II", level: "200L", semester: "spring", major: "NSC" },
      { courseCode: "NSC209", title: "Nursing Ethics and Jurisprudence", level: "200L", semester: "fall", major: "NSC" },
      { courseCode: "NSC210", title: "Mental Health and Psychiatric Nursing I", level: "200L", semester: "spring", major: "NSC" },
      { courseCode: "NSC211", title: "Medical and Surgical Nursing I", level: "200L", semester: "fall", major: "NSC" },
      { courseCode: "NSC212", title: "Information Management and Patient Care Technology", level: "200L", semester: "spring", major: "NSC" },
      { courseCode: "NSC213", title: "Public Health Microbiology & Parasitology/Entomology", level: "200L", semester: "fall", major: "NSC" },
      { courseCode: "NSC214", title: "Pharmacodynamics and Chemotherapy II", level: "200L", semester: "spring", major: "NSC" },
      { courseCode: "NSC215", title: "Oncology Nursing", level: "200L", semester: "fall", major: "NSC" },
      { courseCode: "NSC217", title: "Family Health Nursing", level: "200L", semester: "fall", major: "NSC" },
      { courseCode: "NSC301", title: "Medical Surgical Nursing Practicum III", level: "300L", semester: "fall", major: "NSC" },
      { courseCode: "NSC302", title: "Maternal and Child Health Nursing II", level: "300L", semester: "spring", major: "NSC" },
      { courseCode: "NSC303", title: "Maternal and Child Health Nursing I", level: "300L", semester: "fall", major: "NSC" },
      { courseCode: "NSC304", title: "Maternal and Child Health Nursing Practicum 1", level: "300L", semester: "spring", major: "NSC" },
      { courseCode: "NSC305", title: "Mental Health Nursing II", level: "300L", semester: "fall", major: "NSC" },
      { courseCode: "NSC306", title: "Curriculum Development and Teaching Methodology", level: "300L", semester: "spring", major: "NSC" },
      { courseCode: "NSC307", title: "Research Methods in Nursing", level: "300L", semester: "fall", major: "NSC" },
      { courseCode: "NSC308", title: "Community/Public Health Nursing III", level: "300L", semester: "spring", major: "NSC" },
      { courseCode: "NSC309", title: "Management of Nursing Services", level: "300L", semester: "fall", major: "NSC" },
      { courseCode: "NSC310", title: "Emergency and Disaster Nursing", level: "300L", semester: "spring", major: "NSC" },
      { courseCode: "NSC311", title: "Biostatistics", level: "300L", semester: "fall", major: "NSC" },
      { courseCode: "NSC312", title: "Nursing in Health and Illness II", level: "300L", semester: "spring", major: "NSC" },
      { courseCode: "NSC313", title: "Nursing in Health and Illness I", level: "300L", semester: "fall", major: "NSC" },
      { courseCode: "NSC314", title: "Critical Care Nursing", level: "300L", semester: "spring", major: "NSC" },
      { courseCode: "NSC315", title: "Epidemiology, Disease Control & Surveillance", level: "300L", semester: "fall", major: "NSC" },
      { courseCode: "NSC316", title: "Health Systems, Planning, Management & Administration", level: "300L", semester: "spring", major: "NSC" },
      { courseCode: "NSC317", title: "International and Global Health", level: "300L", semester: "fall", major: "NSC" },
      { courseCode: "NSC401", title: "Community/Public Health Nursing Practicum II", level: "400L", semester: "fall", major: "NSC" },
      { courseCode: "NSC402", title: "Maternal and Child Health Nursing Practicum IV", level: "400L", semester: "spring", major: "NSC" },
      { courseCode: "NSC403", title: "Maternal and Child Health Nursing Practicum II", level: "400L", semester: "fall", major: "NSC" },
      { courseCode: "NSC404", title: "Public/Community Health Nursing IV", level: "400L", semester: "spring", major: "NSC" },
      { courseCode: "NSC405", title: "Maternal and Child Health Nursing III", level: "400L", semester: "fall", major: "NSC" },
      { courseCode: "NSC406", title: "Community/Public Health Nursing Practicum III", level: "400L", semester: "spring", major: "NSC" },
      { courseCode: "NSC407", title: "Health and Nursing Informatics", level: "400L", semester: "fall", major: "NSC" },
      { courseCode: "NSC408", title: "Entrepreneurship in Nursing", level: "400L", semester: "spring", major: "NSC" },
      { courseCode: "NSC409", title: "Nursing Seminars", level: "400L", semester: "fall", major: "NSC" },
      { courseCode: "NSC410", title: "Research Project", level: "400L", semester: "spring", major: "NSC" },
      { courseCode: "NSC411", title: "Health Economics", level: "400L", semester: "fall", major: "NSC" },
      { courseCode: "NSC412", title: "Gerontology/Geriatric Nursing", level: "400L", semester: "spring", major: "NSC" },
      { courseCode: "NSC413", title: "Reproductive Health Nursing", level: "400L", semester: "fall", major: "NSC" },
      { courseCode: "NSC414", title: "Guidance and Counseling in Nursing", level: "400L", semester: "spring", major: "NSC" },
      { courseCode: "NSC415", title: "Nursing Administration and Management", level: "400L", semester: "fall", major: "NSC" },
      { courseCode: "NSC416", title: "Reproductive Health Nursing Practicum", level: "400L", semester: "spring", major: "NSC" },
      { courseCode: "NSC417", title: "Strategies for Innovation in Nursing Education", level: "400L", semester: "fall", major: "NSC" },
      { courseCode: "NSC418", title: "Community Health Nursing", level: "400L", semester: "spring", major: "NSC" },
      { courseCode: "NSC420", title: "Critical Care Nursing", level: "400L", semester: "spring", major: "NSC" },
      { courseCode: "NSC422", title: "Palliatives Care and Rehabilitation Nursing", level: "400L", semester: "spring", major: "NSC" },
      { courseCode: "NSC424", title: "Nursing Education", level: "400L", semester: "spring", major: "NSC" },

      // Public Health courses
      { courseCode: "PHS101", title: "General Biology I", level: "100L", semester: "fall", major: "PHS" },
      { courseCode: "PHS102", title: "General Biology II", level: "100L", semester: "spring", major: "PHS" },
      { courseCode: "PHS103", title: "General Biology Practical I", level: "100L", semester: "fall", major: "PHS" },
      { courseCode: "PHS104", title: "General Biology Practical II", level: "100L", semester: "spring", major: "PHS" },
      { courseCode: "PHS105", title: "General Chemistry I", level: "100L", semester: "fall", major: "PHS" },
      { courseCode: "PHS106", title: "General Chemistry II", level: "100L", semester: "spring", major: "PHS" },
      { courseCode: "PHS107", title: "General Chemistry Practical I", level: "100L", semester: "fall", major: "PHS" },
      { courseCode: "PHS108", title: "General Chemistry Practical II", level: "100L", semester: "spring", major: "PHS" },
      { courseCode: "PHS109", title: "Elementary Mathematics (Algebra & Trigonometry)", level: "100L", semester: "fall", major: "PHS" },
      { courseCode: "PHS110", title: "Fundamentals of Public Health", level: "100L", semester: "spring", major: "PHS" },
      { courseCode: "PHS111", title: "Introduction to Computing", level: "100L", semester: "fall", major: "PHS" },
      { courseCode: "PHS112", title: "Introduction to Public Health Informatics", level: "100L", semester: "spring", major: "PHS" },
      { courseCode: "PHS113", title: "General Physics I (Mechanics)", level: "100L", semester: "fall", major: "PHS" },
      { courseCode: "PHS114", title: "General Physics II – Electricity & Magnetism", level: "100L", semester: "spring", major: "PHS" },
      { courseCode: "PHS115", title: "General Practical Physics I", level: "100L", semester: "fall", major: "PHS" },
      { courseCode: "PHS116", title: "General Practical Physics II", level: "100L", semester: "spring", major: "PHS" },
      { courseCode: "PHS201", title: "Introduction to Public Health", level: "200L", semester: "fall", major: "PHS" },
      { courseCode: "PHS202", title: "Biostatistics", level: "200L", semester: "spring", major: "PHS" },
      { courseCode: "PHS203", title: "Principles of Epidemiology (Infectious Disease Epidemiology and Immunisation Techniques)", level: "200L", semester: "fall", major: "PHS" },
      { courseCode: "PHS204", title: "Demography and Social Statistics in Public Health", level: "200L", semester: "spring", major: "PHS" },
      { courseCode: "PHS205", title: "Anatomy of Upper and Lower Limbs", level: "200L", semester: "fall", major: "PHS" },
      { courseCode: "PHS206", title: "Health Anthropology", level: "200L", semester: "spring", major: "PHS" },
      { courseCode: "PHS207", title: "Introductory Physiology and Blood", level: "200L", semester: "fall", major: "PHS" },
      { courseCode: "PHS208", title: "Public Health Services", level: "200L", semester: "spring", major: "PHS" },
      { courseCode: "PHS209", title: "Biochemistry – General and Medical I", level: "200L", semester: "fall", major: "PHS" },
      { courseCode: "PHS210", title: "Public Health Residency", level: "200L", semester: "spring", major: "PHS" },
      { courseCode: "PHS211", title: "General Microbiology", level: "200L", semester: "fall", major: "PHS" },
      { courseCode: "PHS212", title: "Biochemistry – General and Medical II", level: "200L", semester: "spring", major: "PHS" },
      { courseCode: "PHS213", title: "Human Genetics", level: "200L", semester: "fall", major: "PHS" },
      { courseCode: "PHS214", title: "Renal and Body Fluids Physiology", level: "200L", semester: "spring", major: "PHS" },
      { courseCode: "PHS215", title: "Developmental Psychology", level: "200L", semester: "fall", major: "PHS" },
      { courseCode: "PHS301", title: "Public Health Microbiology & Parasitology/Entomology", level: "300L", semester: "fall", major: "PHS" },
      { courseCode: "PHS302", title: "Health Programme Planning and Evaluation", level: "300L", semester: "spring", major: "PHS" },
      { courseCode: "PHS303", title: "Environmental Health and Public Health Laws", level: "300L", semester: "fall", major: "PHS" },
      { courseCode: "PHS304", title: "Occupational Health and Disaster Management", level: "300L", semester: "spring", major: "PHS" },
      { courseCode: "PHS305", title: "Family and Reproductive Health", level: "300L", semester: "fall", major: "PHS" },
      { courseCode: "PHS306", title: "Community Health Practicum I", level: "300L", semester: "spring", major: "PHS" },
      { courseCode: "PHS307", title: "Introduction to Primary Health Care", level: "300L", semester: "fall", major: "PHS" },
      { courseCode: "PHS308", title: "Public Health Nutrition", level: "300L", semester: "spring", major: "PHS" },
      { courseCode: "PHS309", title: "Health Economics I", level: "300L", semester: "fall", major: "PHS" },
      { courseCode: "PHS310", title: "Health Economics II", level: "300L", semester: "spring", major: "PHS" },
      { courseCode: "PHS311", title: "Public Health Seminars I", level: "300L", semester: "fall", major: "PHS" },
      { courseCode: "PHS312", title: "Public Health Seminars II", level: "300L", semester: "spring", major: "PHS" },
      { courseCode: "PHS313", title: "Epidemiology of Communicable and Non-Communicable Diseases", level: "300L", semester: "fall", major: "PHS" },
      { courseCode: "PHS314", title: "Community/Public Health Nursing II", level: "300L", semester: "spring", major: "PHS" },
      { courseCode: "PHS315", title: "Research Methods in Public Health I", level: "300L", semester: "fall", major: "PHS" },
      { courseCode: "PHS317", title: "Community/Public Health Nursing I", level: "300L", semester: "fall", major: "PHS" },
      { courseCode: "PHS401", title: "Health Policy and Finance", level: "400L", semester: "fall", major: "PHS" },
      { courseCode: "PHS402", title: "Research Project", level: "400L", semester: "spring", major: "PHS" },
      { courseCode: "PHS403", title: "Health Sociology", level: "400L", semester: "fall", major: "PHS" },
      { courseCode: "PHS404", title: "Health Systems, Planning, Management & Administration", level: "400L", semester: "spring", major: "PHS" },
      { courseCode: "PHS405", title: "Community Health Care Practicum II", level: "400L", semester: "fall", major: "PHS" },
      { courseCode: "PHS406", title: "Contemporary Issues in Public Health", level: "400L", semester: "spring", major: "PHS" },
      { courseCode: "PHS407", title: "International and Global Health", level: "400L", semester: "fall", major: "PHS" },
      { courseCode: "PHS408", title: "Bioethics and Health Law", level: "400L", semester: "spring", major: "PHS" },
      { courseCode: "PHS409", title: "Principles of Pharmacology, Therapeutics and Substance Abuse", level: "400L", semester: "fall", major: "PHS" },
      { courseCode: "PHS410", title: "Health Policy and Health System Research Review", level: "400L", semester: "spring", major: "PHS" },
      { courseCode: "PHS411", title: "Internship", level: "400L", semester: "fall", major: "PHS" },
      { courseCode: "PHS412", title: "Advanced Biostatistics", level: "400L", semester: "spring", major: "PHS" },
      { courseCode: "PHS413", title: "Research Methods in Public Health II", level: "400L", semester: "fall", major: "PHS" },
      { courseCode: "PHS414", title: "Human Health and Climate change", level: "400L", semester: "spring", major: "PHS" },
      { courseCode: "PHS415", title: "Epidemiology, Disease Control & Surveillance", level: "400L", semester: "fall", major: "PHS" },
    ];

    const createdCourses = await db
      .insert(CourseSchema)
      .values(
        allCourses.map((course) => ({
          courseCode: course.courseCode,
          title: course.title,
          credits: 3,
          departmentId: deptMap[course.major],
          level: course.level,
          semesterOffered: course.semester,
        }))
      )
      .returning();

    console.log(`✅ Created ${createdCourses.length} courses`);

    console.log("\n✨ Seeding complete!");
    console.log(`\n📊 Summary:`);
    console.log(`   Majors: 14`);
    console.log(`   Courses: ${createdCourses.length}`);

    return true;
  } catch (error) {
    console.error("❌ Seeding failed:", error);
    return false;
  }
}

seedMajorsAndCourses().then((success) => {
  process.exit(success ? 0 : 1);
});
