# Nixpacks configuration for Railway

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
# This will be overridden by Railway service settings
# Each service sets its own start command
cmd = "python src/api/study_buddy_api.py"

